# Generated by Django 4.2.4 on 2023-08-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='studName',
        ),
        migrations.AddField(
            model_name='student',
            name='studFName',
            field=models.TextField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='studLName',
            field=models.TextField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='studMName',
            field=models.TextField(default='', max_length=20),
        ),
    ]
