# Generated by Django 4.2.4 on 2023-08-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0002_remove_student_studname_student_studfname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='studMName',
        ),
        migrations.AlterField(
            model_name='student',
            name='studAddress',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='studAge',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='studClass',
            field=models.IntegerField(default=''),
        ),
    ]
