# Generated by Django 4.2.4 on 2023-08-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0003_remove_student_studmname_alter_student_studaddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='studemail',
            field=models.EmailField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='studpassword',
            field=models.TextField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='studusername',
            field=models.TextField(default='', max_length=20),
        ),
    ]
