# Generated by Django 4.2.4 on 2023-08-05 17:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0005_rename_studemail_student_studemail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='studAge',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='studBirthdate',
            field=models.DateField(default=datetime.datetime(2023, 8, 5, 23, 27, 52, 975433)),
        ),
        migrations.AlterField(
            model_name='student',
            name='studClass',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
