# Generated by Django 4.2.4 on 2023-08-26 18:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0007_alter_student_studbirthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='studBirthdate',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 27, 0, 23, 37, 572949), null=True),
        ),
    ]
