# Generated by Django 4.2.4 on 2023-08-27 03:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0011_alter_student_studbirthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='studBirthdate',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 27, 8, 32, 35, 336552), null=True),
        ),
    ]
